-- MySQL Script generated by MySQL Workbench
-- Wed Jul 10 13:23:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cp_panel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cp_panel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cp_panel` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cp_panel` ;

-- -----------------------------------------------------
-- Table `cp_panel`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cp_panel`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email_address` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `otp` BIGINT NOT NULL,
  `partner_id` INT NOT NULL,
  `last_login` TIMESTAMP NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` INT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` INT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_address_UNIQUE` (`email_address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cp_panel`.`user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cp_panel`.`user_profile` (
  `user_profile_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `phone` BIGINT NULL,
  `dob` DATE NULL,
  `designation` VARCHAR(100) NULL,
  `description` TEXT NULL,
  `image` TEXT NULL,
  `address` TEXT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_id` INT NOT NULL,
  `created_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_id` INT NOT NULL,
  `modified_dtm` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_profile_id`),
  INDEX `u_up_fk_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `u_up_fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `cp_panel`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
